# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['gui_app.py'],
    pathex=[],
    binaries=[],
    # קבצי נתונים שצריכים להישאר ליד ה-exe.
    # .iaa_pdfs/ ו-forecast_models_cache/ לא נכללים בכוונה — אלה תיקיות
    # runtime-write שנוצרות בריצה הראשונה דרך mkdir(exist_ok=True),
    # ו-PyInstaller's _MEIPASS תיקייה זמנית והמשתמש בלאו הכי לא יכול לכתוב לתוכה.
    datas=[
        ('iaa_flight_data.csv', '.'),
        ('migrations', 'migrations'),
    ],
    hiddenimports=[
        'psycopg2',
        'psycopg2.extensions',
        'psycopg2._psycopg',
        'psycopg2.pool',
        'pandas',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.timedeltas',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        'dateutil',
        'dateutil.relativedelta',
        'dateutil.tz',
        'requests',
        'requests.packages.urllib3',
        'PyQt6',
        'PyQt6.QtWidgets',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'qtpy',
        'qtpy.QtWidgets',
        'qtpy.QtCore',
        'qtpy.QtGui',
        'matplotlib',
        'matplotlib.backends.backend_qtagg',
        'matplotlib.backends.backend_qt5agg',
        'scipy',
        'scipy.stats',
        'statsmodels',
        'statsmodels.tsa.statespace.sarimax',
        'prophet',
        'xgboost',
        'pyluach',
        'pyluach.dates',
        'pyluach.hebrewcal',
        'tenacity',
        'bidi',
        'bidi.algorithm',
        'dotenv',
        'calendar',
        'json',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PyQt5', 'tkinter', 'unittest'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PriorityInterface',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='PriorityInterface',
)
